name: code-sync-cloud
on:
    push:
        branches: 
            - tgbot

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - name: Run a command remotely
          uses: docker://evaneos/ssh-action:0.1.0
          with:
           hosts: ${{ secrets.SSH_HOST }}
           user: ${{ secrets.SSH_USER }}
           password: ${{ secrets.SSH_PASSWORD }}
           commands: |
             sudo su
             cd  ${{secrets.REPO_SOURCE}}
             sudo rm tg.env
             sudo git fetch --all 
             sudo git reset --hard origin/tgbot
             sudo echo TGBOT=${{secrets.TGBOT}} > tg.env
             sudo echo TGCHAT=${{secrets.TGCHAT}} >> tg.env
             bash script.sh