name: code-sync-cloud
on:
    push:
        branches: 
            - tgbot

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Run a command remotely
          uses: docker://evaneos/ssh-action:0.1.0
          with:
           hosts: ${{ secrets.SSH_HOST }}
           user: ${{ secrets.SSH_USER }}
           password: ${{ secrets.SSH_PASSWORD }}
           commands: |
             tgbot={{secrets.TGBOT}}
             tgchat={{secrets.TGCHAT}}
             cd  ${{secrets.REPO_SOURCE}}
             sudo git checkout tgbot
             sudo git pull
             sudo chmod +x script.sh
             ./script.sh